USE streamcart;

-- REVENUE KPI 
-- Revenue = Net sales value generated from completed orders after discounts.
SELECT
ROUND(SUM(quantity * unit_price * (1-discount_pct/100)),2) AS total_revenue
FROM orders
WHERE status='Completed';

-- GROSS PROFIT 
-- Profit generated after product cost deduction.
SELECT
ROUND(SUM((p.selling_price-p.cost_price)* o.quantity),2) AS gross_profit
FROM orders o
JOIN products p
ON o.product_id=p.product_id
WHERE o.status='Completed';

-- AVERAGE ORDER VALUE 
-- Average revenue generated per completed order.
SELECT
ROUND(SUM(quantity * unit_price * (1-discount_pct/100)) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM orders
WHERE status='Completed';

-- CUSTOMER LIFETIME VALUE 
-- Total revenue generated by a customer across all completed orders.
SELECT
customer_id,
ROUND(SUM(quantity * unit_price * (1-discount_pct/100)), 2) AS customer_lifetime_value
FROM orders
WHERE status='Completed'
GROUP BY customer_id
ORDER BY customer_lifetime_value DESC;

-- ACTIVE CUSTOMERS 
-- Customers who placed at least one completed order within last 90 days from latest available order date
WITH max_order_date AS
(
    SELECT MAX(order_date) AS latest_order_date
    FROM orders
)

SELECT
COUNT(DISTINCT o.customer_id)
AS active_customers
FROM orders o
CROSS JOIN max_order_date m
WHERE o.status='Completed'
AND o.order_date >= DATE_SUB(
        m.latest_order_date,
        INTERVAL 90 DAY
);

-- CHURNED CUSTOMERS 
-- Customers with no completed order in last 180 days of last available date 
WITH max_order_date AS 
(
SELECT MAX(order_date) AS last_order_date 
FROM ORDERS
),

customer_last_order AS
(
    SELECT
        customer_id,
        MAX(order_date) AS last_order
    FROM orders
    WHERE status='Completed'
    GROUP BY customer_id
)

SELECT COUNT(*) AS churned_customers
FROM customer_last_order c
CROSS JOIN max_order_date m
WHERE DATEDIFF(
    m.last_order_date,
    c.last_order
) > 180;

-- CHURN RATE 
-- Percentage of customers classified as churned.
WITH max_order_date AS (
    SELECT MAX(order_date) AS latest_order_date
    FROM orders
),

customer_last_order AS
(
    SELECT customer_id, MAX(order_date) AS last_order_date
    FROM orders
    WHERE status = 'Completed'
    GROUP BY customer_id
)

SELECT
ROUND(100 * SUM(CASE WHEN DATEDIFF(m.latest_order_date,c.last_order_date) > 180 THEN 1 ELSE 0 END) / COUNT(*),2) AS churn_rate_pct
FROM customer_last_order c
CROSS JOIN max_order_date m;

-- SUBSCRIPTION REVENUE 
-- Recurring revenue generated through subscriptions.
SELECT
ROUND(SUM(monthly_fee), 2) AS subscription_revenue
FROM subscriptions;

-- AVERAGE CSAT
-- Average customer satisfaction score across resolved tickets.
SELECT
ROUND(AVG(csat_score), 2) AS average_csat
FROM support_tickets;

-- SLA BREACH RATE 
-- Percentage of tickets violating SLA targets.
WITH sla_data AS
(
SELECT
CASE 
WHEN priority='Critical' AND DATEDIFF(resolved_date,created_date)>1 THEN 1
WHEN priority='High' AND DATEDIFF(resolved_date,created_date)>3 THEN 1
WHEN priority='Medium' AND DATEDIFF(resolved_date,created_date)>7 THEN 1
ELSE 0
END AS breached
FROM support_tickets
WHERE resolved_date IS NOT NULL
)

SELECT
ROUND(100 * SUM(breached) / COUNT(*) ,2) AS sla_breach_rate
FROM sla_data;

-- MONTHLY RECURRING REVENUE 
-- predictable monthly revenue generated from active subscription plans.
WITH latest_order_date AS
(
    SELECT MAX(order_date) AS max_date
    FROM orders
)

SELECT
ROUND(SUM(monthly_fee), 2) AS monthly_recurring_revenue
FROM subscriptions s
CROSS JOIN latest_order_date d
WHERE s.end_date >= d.max_date;

-- CUSTOMER RETENTION RATE 
-- Percentage of customers who remained active during the evaluation period.
WITH max_order_date AS(
SELECT MAX(order_date) AS latest_order_date
FROM orders
),

active_customers AS
(
    SELECT COUNT(DISTINCT customer_id) AS active_count
    FROM orders o
    CROSS JOIN max_order_date m
    WHERE o.status = 'Completed'
    AND o.order_date >= DATE_SUB(m.latest_order_date, INTERVAL 90 DAY)),

total_customers AS
(
    SELECT COUNT(*) AS total_count
    FROM customers
)

SELECT
ROUND((a.active_count * 100.0) / t.total_count, 2) AS retention_rate_pct
FROM active_customers a
CROSS JOIN total_customers t;